### ISSUE TITLE
Prise de contact avec le consulat du cameorun à Marseille pour l'intégration au site

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#185]
En cours par victor

**Comment by fabiolatagne97** [comment]
@billmetangmo oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by Vkongue** [comment]
Rendez-vous avec le consulat prévu vendredi 13/09/2024

**Comment by billmetangmo** [comment]
@Vkongue tu peux mettre à jours les infos sur l'issue ?

**Comment by billmetangmo** [comment]
@Vkongue retour:

C’était déjà le nouveau process?
En gros depuis le nouveau process les usager son notifier par sms des que leur passeport arrive à Marseille
Du coup les gens n’ont réellement plus besoins d’aller sur le site web vérifier
Alors maintenant les dames (mamie) qui bossent la-bas demande la page juste pour se faciliter la recherche mais c’est une pratique qui va changer bientôt
Ceci impacte directement la pérénite de la solution qu’on propose

**Comment by billmetangmo** [comment]
Vote du freeze du projet.
