### ISSUE TITLE
UI test

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#21]
Using uirecorder & macaca server

**Comment by billmetangmo** [comment]
Use cypress instead for web/mobile.

**Comment by billmetangmo** [comment]
https://github.com/ripienaar/free-for-dev#testing ( plus exhasufif - si possible prendre 1 opensource )

**Comment by billmetangmo** [comment]
https://mmazzarolo.com/blog/2022-09-09-visual-regression-testing-with-playwright-and-github-actions/ ( playwright / puppeteer )

**Comment by billmetangmo** [comment]
https://testcafe.io/

**Comment by billmetangmo** [comment]
https://www.rainforestqa.com/

**Comment by tsafacjo** [comment]
What is the goal ?
Simulate an user behavior who goes on the  registration page types name and the email then confirms, right ?

**Comment by billmetangmo** [comment]
Yes. And the chosen tool should be able to test it regularly. That's will be life line of the app.

**Comment by billmetangmo** [comment]
dupliqué avec #90
