### ISSUE TITLE
Creating and Using Terraform Layers

### ISSUE THREAD

**Issue by pdjiela** [mongulu-cm/mtchoun-mouh#29]
Transform main terraform code into modules to make this code easy re-usable to create another environment

**Comment by billmetangmo** [comment]
Utiliser les terraform layer pour le début: API(API GATEWAY) - DB (DYNAMODB)- CODE(AWS LAMBDA) ?

**Comment by billmetangmo** [comment]
https://brendanthompson.com/posts/2021/11/my-terraform-development-workflow

**Comment by billmetangmo** [comment]
Perte de tout le travail effectué dans le coud car le travail n'était pas push. Nécessaire de rappeler lors de l'onboarding la nécessite de pusher à chaque fois son travail. A lon terme avoir un mécanisme de rappel https://github.com/mongulu-cm/lobembe/issues/45

**Comment by billmetangmo** [comment]
https://blog.wescale.fr/terraform-layering-pourquoi-et-comment

**Comment by billmetangmo** [comment]
abandonné
