### ISSUE TITLE
Set up an environment with gitpod

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#49]
https://gitpod.io/
Free until 50 hours which is sufficient for work [ https://www.gitpod.io/pricing ]

**Comment by GoldenScientist** [comment]
good i'm working on it

**Comment by GoldenScientist** [comment]
veux tu que je fasse un readme comme jetbrains avec le logo?

**Comment by billmetangmo** [comment]
Oui tu peux faire ça. Pas récrire un Readme mais créer une branche à partir de main. Et dans cette branche, tu rajoutes le logo

**Comment by GoldenScientist** [comment]
ok
