### ISSUE TITLE
Send a real email to say that user has been registered

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#61]
Instead of the previous mail which was because we don't have prod access to SES

**Comment by billmetangmo** [comment]
Currently when user registred, we verify email like this  https://github.com/mongulu-cm/mtchoun-mouh/blob/06e94c24b98d11fbe71a9d325a88689c9462d300/api/registre.py#L32

We were doing so because we did not have access to Amazon SES ( AWS service to send mail) **production mode** which allows to send email to anyuser. But we needed to verify mail before which means sending **a weird message** like this:
![Capture d’écran du 2023-01-04 13-24-58](https://user-images.githubusercontent.com/25366207/210555476-ea247d59-5920-49c7-89b4-6b783d7c6de1.png)
**And as you can see above, the user has to validate it within 24h ...**

Now, we want to replace the verification by a mail send to a user . You can inspire and add your code  to this function https://github.com/mongulu-cm/mtchoun-mouh/blob/06e94c24b98d11fbe71a9d325a88689c9462d300/api/notify.py#L25

Le message reçu suivra ce template:
```
Hello <nom>

Merci de t'être inscrit à mtchoun-mouh (le service de notification de passeports du collectif mongulu) ! Nous avons bien enregistré ton adresse e-mail et ton nom complet, et nous t'enverrons une notification dès que ton passeport sera sur les listes du consulat du Cameroun à Marseille. 

En attendant, n'hésite pas à nous contacter si tu as des questions ou si vous avez besoin d'aide. Nous te remercions pour ta confiance et nous nous réjouissons de pouvoir t'aider à te libérer l'esprit de la visite régulière du site du consulat.
```

**Comment by billmetangmo** [comment]
Le logo 
![logo_upscayled_4x_miniature](https://user-images.githubusercontent.com/25366207/213664083-d57d05fc-1b3d-4825-a70d-b40aa2acb1a7.jpeg)

**Comment by tsafacjo** [comment]
@billmetangmo  j'aurais besoin d'une adresse email pour que les utilisateurs puissent nous contacter ?
l'adresse actuelle n'est pas très digest :
general.4ba9da54de788677fa6b62cca72ddfe0.show-sender@streams.zulipchat.com

**Comment by billmetangmo** [comment]
Effectivement.
ET si dans la partie contact mail, tu mettais un mailto plutôt .
C'est ce que j'ai fait sur le site https://www.mongulu.cm/ ( CONTACT tout en bas)

Sinon j'ai créé l'an passé une page facebook au nom du collectif en transformant une page que j'avais déjà https://www.facebook.com/CollectifMongulu . TU peux tout aussi mettre cette page pour qu'il nous envoie un message.

Mais je suis ouvert à une autre solution.

**Comment by tsafacjo** [comment]
C'est comme si j'ai oublié un élément.
SI je comprends dans le mail, on devrait avoir un mail qui permet de valider son adresse mail ?
