### ISSUE TITLE
Check readiness after deployment of the html website

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#67]

**Comment by billmetangmo** [comment]
https://percy.io/visual-testing
or https://github.com/simonw/shot-scraper & imgdupes

**Comment by billmetangmo** [comment]
For 200 check https://github.com/marketplace?type=actions&query=health+check+

**Comment by billmetangmo** [comment]
https://github.com/lost-pixel/lost-pixel
https://github.com/garris/BackstopJS
https://nightwatchjs.org/

**Comment by billmetangmo** [comment]
https://www.uier.eu/

**Comment by ngnnpgn** [comment]
Pas de solution trouvée pour set la sortie du terraform output....

**Comment by billmetangmo** [comment]
> Pas de solution trouvée pour set la sortie du terraform output....
Tu veux dire pour avoir juste l' URL ?

**Comment by billmetangmo** [comment]
ChatGPT me propose :
`url=$(terraform output | grep website_url | awk '{print $3}')`
et ça a fonctionné.

![gr31sx](https://user-images.githubusercontent.com/25366207/220741664-274c6303-8ec6-495b-a304-75955cd11b3e.png)

**Comment by billmetangmo** [comment]
Il faudra ajouter  #67 sur tous tes commit.

**Comment by ngnnpgn** [comment]
il faut desactiver le wrapper lors de l'installation de terraform pour avoir une sortie standard sans "enveloppe".
 comme ceci:
with:
     terraform_wrapper: false
