### ISSUE TITLE
Check liveness after site deployment

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#90]
- https://github.com/lost-pixel/lost-pixel
- https://github.com/garris/BackstopJS
- https://nightwatchjs.org/
- https://www.uier.eu/
- https://percy.io/visual-testing ( visual regression testing tools)
- https://github.com/simonw/shot-scraper & imgdupes
- Using uirecorder & macaca server
- Use cypress instead for web/mobile
- Also https://meticulous.ai/ ( une approche vraiment nouvelle)
- https://github.com/ripienaar/free-for-dev#testing ( plus exhasufif - si possible prendre 1 opensource )
- https://mmazzarolo.com/blog/2022-09-09-visual-regression-testing-with-playwright-and-github-actions/ ( playwright / puppeteer )
- https://testcafe.io/
- https://www.rainforestqa.com/

The choosen solution should also be able to be use for post-ops monitoring
- Cloudwatch syntetic monitoring: https://catalog.us-east-1.prod.workshops.aws/workshops/31676d37-bbe9-4992-9cd1-ceae13c5116c/en-US/synthetics

**Comment by tsafacjo** [comment]
intresting , all this new tools.

**Comment by billmetangmo** [comment]
THis task is linked to this one https://github.com/mongulu-cm/mtchoun-mouh/issues/21

**Comment by billmetangmo** [comment]
And should not be done before #67

**Comment by billmetangmo** [comment]
@tsafacjo si ça t'intéresse tu pourras regarder ça après la #61

**Comment by tsafacjo** [comment]
Ok.

**Comment by tsafacjo** [comment]
As we have to keep using open source project I 'm constraint to skip all the previous tools as there are not open source and the free version is not engouh.
I will go for a specify no code solution Selenium IDE  to record the tests by using the browser then I will export the test in python file.

**Comment by billmetangmo** [comment]
Cloudwatch synthetics have an UI recorder

**Comment by billmetangmo** [comment]
Créer un compte sur https://testmail.app/ et check le mail reçu par API
