### ISSUE TITLE
Add website/product analytics

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/mtchoun-mouh#93]
For website matomo/plausible 
For product analytics: posthog

**Comment by tsafacjo** [comment]
can I have more informations ?

**Comment by billmetangmo** [comment]
Yes, I will give you them but we need a call. We will planify it

**Comment by billmetangmo** [comment]
closes with https://github.com/mongulu-cm/mtchoun-mouh/commit/79143921a1ab2407f6974e6cf3023794ebe1c6b4
